### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by XiaoqiLu** [XiaoqiLu/futility-analysis#1]
- [] Add revenue() and cost() as input, rather than bcRatio. (as actual cost)
- [] Add constraints for fix t, N0
- [] Consider d as distribution
- [] Design() as interactive
